---

- name: debug output of extra_ports
  debug:
    msg: '{{ vault_shadowsocks_port }} {{ vault_kcp_port }}'
    verbosity: 2

- name: Add kcptun port to firewall whitelist
  iptables:
    chain: INPUT
    ctstate: NEW
    match: udp
    protocol: udp
    in_interface: eth0
    destination_port: '{{ vault_kcp_port }}'
    jump: ACCEPT

- name: Remove ss port from firewall whitelist
  iptables:
    chain: INPUT
    ctstate: NEW
    match: tcp
    protocol: tcp
    in_interface: eth0
    destination_port: '{{ vault_shadowsocks_port }}'
    jump: ACCEPT
    state: absent

- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install shadowsocks related packages from backports repository
  apt:
    name: '{{ item }}'
    default_release: '{{ ansible_distribution_release }}-backports'
    state: latest
  with_items: '{{ ss_packages }}'

- name: configure shadowsocks
  template:
    src: config.j2
    dest: '/etc/shadowsocks-libev/{{ ansible_hostname }}.json'
  notify:
    - restart shadowsocks

- name: Enable and start ss services
  service:
    name: '{{ item }}'
    state: started
    enabled: true
  with_items:
    - 'shadowsocks-libev-server@{{ ansible_hostname }}'
    - supervisor

- name: configure supervisor
  template:
    src: kcptun.j2
    dest: /etc/supervisor/conf.d/kcptun.conf
  notify:
    - restart kcptun via supervisorctl
