---

- name: debug output of extra_ports
  debug:
    msg: '{{ vault_shadowsocks_port }} {{ vault_kcp_port }}'
    verbosity: 2

- name: Accept some tcp connections
  iptables:
    chain: INPUT
    ctstate: NEW
    match: '{{ item.proto }}'
    protocol: '{{ item.proto }}'
    in_interface: eth0
    destination_port: '{{ item.port }}'
    jump: ACCEPT
  with_items:
    - { port: '{{ vault_shadowsocks_port }}', proto: tcp }
    - { port: '{{ vault_kcp_port }}', proto: udp }


- name: Install shadowsocks related packages from backports repository
  apt:
    name: '{{ item }}'
    default_release: '{{ ansible_distribution_release }}-backports'
    state: latest
  with_items: '{{ ss_packages }}'

- name: configure shadowsocks
  template:
    src: config.j2
    dest: '/etc/shadowsocks-libev/{{ ansible_hostname }}.json'
  notify:
    - restart shadowsocks

- name: Make sure ss service is enabled and started
  service:
    name: '{{ item }}'
    state: started
    enabled: true
  with_items:
    - 'shadowsocks-libev-server@{{ ansible_hostname }}'
    - supervisor

- name: configure supervisor
  template:
    src: kcptun.j2
    dest: /etc/supervisor/conf.d/kcptun.conf
  notify:
    - restart kcptun via supervisorctl
