---

- hosts: fqservers
  tasks:
  - import_role:
      name: common
    tags: always
  - import_role:
      name: firewall
    become: yes
    tags: fw
  - import_role:
      name: ss
    become: yes
    tags: ss
