---

- name: Accept loopback connections
  iptables:
    chain: INPUT
    in_interface: lo
    jump: ACCEPT

- name: Accept related and established connections
  iptables:
    chain: INPUT
    ctstate: ESTABLISHED,RELATED
    jump: ACCEPT

- name: Remove plain ports from firewall whitelist
  iptables:
    chain: INPUT
    ctstate: NEW
    match: tcp
    protocol: tcp
    in_interface: eth0
    destination_port: "{{ item }}"
    jump: ACCEPT
    state: absent
  with_items:
    - 22
    - 80

- name: Open public service ports
  iptables:
    chain: INPUT
    ctstate: NEW
    match: "{{ item.proto|default('tcp') }}"
    protocol: "{{ item.proto|default('tcp') }}"
    in_interface: eth0
    destination_port: "{{ item.port }}"
    jump: ACCEPT
  with_items:
    - { port: 443 }
    - { port: "{{ vault_common_sshd_port }}" }
    - { port: "{{ vault_mosh_port_range }}", proto: udp }

- name: Set INPUT policy
  iptables:
    chain: INPUT
    policy: DROP

- name: Set FORWARD policy
  iptables:
    chain: FORWARD
    policy: DROP

- name: setup iptables network hooks
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0755
  with_items:
    - { src: iptables.preup, dest: /etc/network/if-pre-up.d/iptables }
    - { src: iptables.postdown, dest: /etc/network/if-post-down.d/iptables }
...
